---
title: "Untitled"
author: "Amin Yakubu"
date: "11/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
library(httr)
library(plotly)
```

The last official census in the USA was in 2010. We will use the 2017 United States Census Bureau estimate population for the years of 2017, 2016, 2015 and 2014 as we do not expect a significant population change. 

```{r}
url = "https://www.census.gov/quickfacts/fact/table/newyorkcitynewyork,bronxcountybronxboroughnewyork,kingscountybrooklynboroughnewyork,newyorkcountymanhattanboroughnewyork,queenscountyqueensboroughnewyork,richmondcountystatenislandboroughnewyork/PST045217"

nyc_population = read_html(url) %>%  html_nodes(css = "table") %>% .[[1]] %>% 
  html_table(header = TRUE) %>% as.tibble() %>% 
  janitor::clean_names()

names(nyc_population)[1:7] = c("estimate_date", "new_york_city", "bronx", "brooklyn", "manhattan", "queens", "staten_island")

nyc_population = nyc_population %>% 
  gather(key = boro_nm, value = population, estimate_date:staten_island) %>% 
  mutate(population = if_else(population == "Population estimates, July 1, 2017,  (V2017)", "2017", population),
         population = as.numeric(gsub("," , "", population)))

```

```{r}
crime_df = readRDS(file = "datasets/nyc_felony_misdemeanor.rds") 

crime_df = crime_df %>% 
  mutate(boro_nm = if_else(boro_nm == "staten island", "staten_island", boro_nm))
```

Crime rates in categories (felony, misdemeanor) by borough

```{r}
grouped_df = crime_df %>% group_by(boro_nm, law_cat_cd, year) %>% 
  summarise(number = n())

full = left_join(grouped_df, nyc_population, by = "boro_nm") %>% 
  mutate(crime_rate = (number/population)*100)

x = ggplot(full, aes(x = year, y = crime_rate, color = boro_nm)) + 
  geom_line() + 
  facet_grid(~law_cat_cd)

ggplotly(x)

```



























































