---
title: "Code for Exploratory Analysis 1 - Reported Length of Event/Crime by Borough"
---

<br>
#**Code**

<br>
This is the code for the first exploratory analysis in which we examined the length of the reported event/crime by borough.

<br>
```{r code_date_setup}

library(tidyverse)
devtools::install_github("thomasp85/patchwork")
library(patchwork)
```

<br>
```{r code_date_tidy_crime_data}
crime_df = readRDS(file = "datasets/nyc_felony_crimes.rds")

crime_data = crime_df %>% 
  janitor::clean_names() %>%
  sample_n(1000) %>% 
  mutate(time_diff = (difftime(cmplnt_to_dt, cmplnt_fr_dt))) %>% 
  mutate(time_diff2 = (as.numeric(cmplnt_to_dt - cmplnt_fr_dt, units = "days", na.rm = TRUE))) %>% 
  select(cmplnt_fr_dt, cmplnt_to_dt, law_cat_cd, time_diff, time_diff2, boro_nm)

head(crime_data)
```

<br>
```{r code_date_crime_data_table}
crime_table = 
  crime_data %>% 
  knitr::kable(digits = 2)

head(crime_table, 12)
```

<br>
```{r code_date_length_of_time_of_reported_event}
crime_data2 <- crime_data[complete.cases(crime_data),]

crime_graph2 = 
  crime_data2 %>% 
  group_by(boro_nm, law_cat_cd) %>% 
  ggplot(aes(x = boro_nm, y = time_diff2, color = law_cat_cd)) + 
  geom_point() +
    labs(
    title = "Spread of Times of Reported Event, By Borough",
    x = "Borough",
    y = "Length of Reported Event",
    caption = "Data from the crime_data file"
    ) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom")

crime_graph2
```

