---
title: "Exploratory Analysis"
author: "Jyoti Ankam"
date: "November 17, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
library(plotly)
```

```{r}

crime_df = readRDS(file = "datasets/nyc_felony_misdemeanor.rds")

```

```{r}

url = "https://www.census.gov/quickfacts/fact/table/newyorkcitynewyork,bronxcountybronxboroughnewyork,kingscountybrooklynboroughnewyork,newyorkcountymanhattanboroughnewyork,queenscountyqueensboroughnewyork,richmondcountystatenislandboroughnewyork/PST045217"
boro_pop = read_html(url)

boro_pop %>%
  html_nodes(css = "table")

pop_df = (boro_pop %>% html_nodes(css = "table")) %>% 
  .[[1]] %>%
  html_table() %>% 
  as_tibble() %>% 
 janitor::clean_names()

names(pop_df)[1:7] = c("estimate_date", "new_york_city", "bronx", "brooklyn", "manhattan", "queens", "staten_island")

pop_df = pop_df %>% 
  gather(key = boro_nm, value = population, estimate_date:staten_island) %>% 
  mutate(population = if_else(population == "Population estimates, July 1, 2017,  (V2017)", "2017", population),
         population = as.numeric(gsub("," , "", population)))

```

```{r}
nycc_df = crime_df %>% 
  mutate(boro_nm = if_else(boro_nm == "staten island", "staten_island", boro_nm))
```
 
Looking at the individual offenses by borough over the four years:
```{r}

crime_df %>% 
  distinct(pd_cd) %>% 
  count()

combined_df = nycc_df %>% group_by(boro_nm, pd_cd, year) %>% 
  summarise(count = n())

 full = left_join(combined_df, pop_df, by = "boro_nm") %>% 
  mutate(off_rate = ((count/population)*100))
 
 full %>% select(-count, -population) %>% 
   group_by(boro_nm, pd_cd, year) %>% 
  head(arrange(desc(pd_cd)), n = 1) 
  ggplot(aes(aes(x = year, y = pd_cd, color = boro_nm))) +
  geom_col() +
  theme(legend.position = "none") +
  labs(
    title = "Offense rate",
    x = "Year",
    y = "Number of offenses",
    caption = "NYC crime by borough"
  )

 
 trend = ggplot(full, aes(x = year, y = off_rate, color = boro_nm)) + 
 geom_point() + 
 theme(legend.position = "bottom") +
  labs(
    x = "Year",
    y = "Number of offenses",
    caption = "NYC_Crime"
  )
ggplotly(trend)

trend = ggplot(full, aes(x = year, y = ofns_desc, color = boro_nm)) + 
 geom_line() + 
 theme(legend.position = "bottom") +
  labs(
    x = "Year",
    y = "Number of offenses",
    caption = "NYC_Crime"
  )
ggplotly(trend)

```
