---
title: "Explore_Yaa"
author: "Yaa Klu"
date: "11/30/2018"
output: html_document
---

```{r exp_yaa_lib}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(eval = FALSE)
```




```{r}
library(tidyverse)
```



```{r exp_yaa_data}
felony_crime = readRDS(file = "./datasets/sex_drug_weapons.rds")

overall_felony = readRDS(file = "./datasets/nyc_felony_crimes.rds")

complete_data = inner_join(overall_felony, felony_crime, by = "cmplnt_num") %>%
  janitor::clean_names(dat = .)
```



Number of crimes in 3 crime groups

```{r}
complete_data %>%
  group_by(crime_group) %>%
  summarise(number = n()) %>%
  arrange(desc(number)) %>%
  knitr::kable()
```


** For sex related and weapon related crimes what are the dempgraphics of the victims?**


****
By victim's age group
```{r}
complete_data %>%
  filter(crime_group == "Sex-Related") %>%
  filter(!is.na(vic_age_group), vic_age_group != "unknown") %>% 
  group_by(vic_age_group) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 

complete_data %>%
  filter(crime_group == "Weapon-Related") %>%
  filter(!is.na(vic_age_group), vic_age_group != "unknown") %>% 
  group_by(vic_age_group) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 

complete_data %>%
  filter(crime_group == "Drug-Related") %>%
  filter(!is.na(vic_age_group), vic_age_group != "unknown") %>% 
  group_by(vic_age_group) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 


```



By victim's sex
```{r}
complete_data %>%
  filter(crime_group == "Sex-Related") %>%
  filter(!is.na(vic_sex.y), vic_sex.y != "unknown") %>% 
  group_by(vic_sex.y) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 

complete_data %>%
  filter(crime_group == "Weapon-Related") %>%
  filter(!is.na(vic_sex.y), vic_sex.y != "unknown") %>% 
  group_by(vic_sex.y) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 

complete_data %>%
  filter(crime_group == "Drug-Related") %>%
  filter(!is.na(vic_sex.y), vic_sex.y != "unknown") %>% 
  group_by(vic_sex.y) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 
```


Victim's race

```{r}
complete_data %>%
  filter(crime_group == "Sex-Related") %>%
  filter(!is.na(vic_race.y), vic_race.y != "unknown") %>% 
  group_by(vic_race.y) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 

complete_data %>%
  filter(crime_group == "Weapon-Related") %>%
  filter(!is.na(vic_race.y), vic_race.y != "unknown") %>% 
  group_by(vic_race.y) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 

complete_data %>%
  filter(crime_group == "Drug-Related") %>%
  filter(!is.na(vic_race.y), vic_race.y != "unknown") %>% 
  group_by(vic_race.y) %>%
  summarise(number = n()) %>% arrange(desc(number)) %>% 
  knitr::kable() 
```










