---
title: "Final_project"
author: "Yaa Klu"
date: "11/17/2018"
output: github_document
---

```{r}
crime_nyc = readRDS(file = "datasets/nyc_felony_misdemeanor.rds")
```
 
```{r}
library(tidyverse)
```


**Crime category by race/ethnicity, age, sex and other sociodemographics**
** top ten offense, general chracteristics**
** top 5, general characteristics**
**filter out unknown and analyze top 5 crimes for unknowns**


Removing missing variables
```{r}
com_crime_nyc = crime_nyc %>% 
  janitor::clean_names(dat = .) %>% 
  filter(!is.na(susp_sex)) %>%
  filter(!is.na(susp_age_group)) %>%
  filter(!is.na(vic_sex)) %>%
  filter(!is.na(vic_age_group)) %>%
  filter(!is.na(vic_race)) %>%
  filter(!is.na(susp_race))
```


Highest number of crimes (top 5)
```{r}
com_crime_nyc %>%
  distinct(pd_desc) %>%
  count()

com_crime_nyc %>%
  group_by(pd_desc, pd_cd) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 
```


Suspect Age
```{r}
com_crime_nyc %>%
  group_by(susp_age_group) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 
```

Suspect Sex
```{r}
com_crime_nyc %>%
  group_by(susp_sex) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(3, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 

```

Victim's sex
```{r}
com_crime_nyc %>%
  group_by(vic_sex) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(3, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 
```

Victim's age
```{r}
com_crime_nyc %>%
  group_by(vic_age_group) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 
```

Suspect's age
```{r}
com_crime_nyc %>%
  group_by(susp_race) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 
```


Victim's race
```{r}
com_crime_nyc %>%
  group_by(vic_race) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable()
```

Suspect's race
```{r}
com_crime_nyc %>%
  group_by(pd_desc, susp_race) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable()

```


```{r}
com_crime_nyc %>%
  group_by(susp_race, vic_race) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable()
```


```{r}
com_crime_nyc %>%
  group_by(susp_race, pd_desc) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable()
```


```{r}
com_crime_nyc %>%
  group_by(pd_desc, susp_age_group) %>%
  summarise(number = n()) %>%
  ungroup() %>%
  top_n(5, number) %>%
  arrange(desc(number)) %>%
  knitr::kable() 
```


```{r}
filter(com_crime_nyc, susp_age_group == 'unknown')


```

