---
title: "Sex-Related, Weapon-Related & Drug-Related Crimes in NYC"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r flex_libraries}
library(flexdashboard)
library(plotly)
library(tidyverse)
#library(htmltools)
#library(htmlwidgets)
library(leaflet)
library(leaflet.extras)
#library(rgdal)
#if (!require(geojsonio)) {
#    install.packages("geojsonio")
#    library(geojsonio)
#}
library(sp)
library(maps)
#library(ggmap)
#library(maptools)
library(chron)
library(lubridate)
library(rvest)
library(tools)
```

```{r flex_data}
###Dataset for 2017 with addresses
crimes_df = readRDS(file = "./datasets/all_sex_drug_weapon_zip_2017.rds")

```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A: Distribution for sex-related, drug-related and weapon-related felonies for 2017 by Zipcode

```{r flex_chatA}
map_json = geojson_read("./datasets/nyc_zip_map.geojson", what = "sp")

crimes_df = crimes_df %>% 
  mutate(zipcode = str_extract(zip, "[0-9][0-9][0-9][0-9][0-9]"),
         boro_nm = toTitleCase(boro_nm))

crime_group_sum = crimes_df %>% group_by(zipcode) %>% summarize(number = n())

map_json@data <-  
  map_json@data %>% left_join(crime_group_sum, by = c("postalCode" = "zipcode")) %>% 
  mutate(number = as.numeric(number)) %>% 
  mutate(number = if_else(is.na(number), 0, number))

# create color palette with colorNumeric()
nyc_pal <- colorNumeric("Blues", domain = map_json@data$number)

map_json %>% 
  leaflet() %>% 
  addProviderTiles("OpenStreetMap.BlackAndWhite", options = providerTileOptions(opacity = 0.4)) %>% 
  setView(lat = 40.7, lng = -73.9, zoom = 11) %>% 
  addPolygons(weight = 1, fillColor = ~ nyc_pal(number),
              color = "gray",
              fillOpacity = 3, opacity = 1, 
              smoothFactor = 0.2, 
  # add labels that display mumber
              label = ~ paste(postalCode, borough, ':', number, sep = '\n'),
              # highlight polygons on hover
              highlight = highlightOptions(weight = 2, color = "black",
              bringToFront = TRUE)) %>% 
   addLegend(pal = nyc_pal,
                   values = c(0:305),
                   opacity = 0.75,
                   title = "Number of incident crimes ",
                   position = "topleft")
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B: Trend of Crime rate

```{r flex_chartB}
sex_drug_weapons = readRDS(file = "./datasets/sex_drug_weapons.rds")

url = "https://www.census.gov/quickfacts/fact/table/newyorkcitynewyork,bronxcountybronxboroughnewyork,kingscountybrooklynboroughnewyork,newyorkcountymanhattanboroughnewyork,queenscountyqueensboroughnewyork,richmondcountystatenislandboroughnewyork/PST045217"

nyc_population = read_html(url) %>%  html_nodes(css = "table") %>% .[[1]] %>% 
  html_table(header = TRUE) %>% as.tibble() %>% 
  janitor::clean_names()

names(nyc_population)[1:7] = c("estimate_date", "new_york_city", "bronx", "brooklyn", "manhattan", "queens", "staten_island")

nyc_population = nyc_population %>% 
  gather(key = boro_nm, value = population, estimate_date:staten_island) %>% 
  mutate(population = if_else(population == "Population estimates, July 1, 2017,  (V2017)", "2017", population),
         population = as.numeric(gsub("," , "", population)))

grouped_df = sex_drug_weapons %>% group_by(boro_nm, year) %>% 
  summarise(number = n())

full = left_join(grouped_df, nyc_population, by = "boro_nm") %>% 
  mutate(crime_rate = (number/population)*100)

x = full %>% filter(!is.na(boro_nm)) %>% 
  ggplot(aes(x = year, y = crime_rate, color = boro_nm)) + 
  geom_point() + geom_line(size = 1) +
  labs(x = "Year",
       y = "Crime rate",
       legend) + viridis::scale_color_viridis(
      name = "Borough", 
      discrete = TRUE
    ) + theme_classic()

ggplotly(x)
```

### Chart C: Distribution of victims of sex, drug and weapon-related crimes by race/ethnicity from 2014 - 2017

```{r flex_chartC}
sex_drug_weapons = readRDS(file = "./datasets/sex_drug_weapons.rds")

season_df = sex_drug_weapons %>% 
  mutate(quarter = as.numeric(quarter(cmplnt_fr_dt)),
         month = months(cmplnt_fr_dt),
         month = forcats::fct_relevel(month, c("January", "February", "March", "April", "May", "June", "July",
                                               "August", "September", "October", "November", "December")),
         day = weekdays(cmplnt_fr_dt),
         day = forcats::fct_relevel(day, c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")),
         cmplnt_fr_tm = lubridate::hms(as.character(cmplnt_fr_tm)),
         hour = hour(cmplnt_fr_tm)) %>% select(-cmplnt_fr_tm)

#### Filtering out unknown victim race
p = season_df %>% filter(vic_race != "unknown") %>% 
  group_by(vic_race, boro_nm) %>% summarize(number = n()) %>% 
  ggplot(aes(x = reorder(vic_race, number), y = number, fill = vic_race)) + geom_col()  + 
  theme(legend.position = "left", axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(y = "Total Number") + viridis::scale_fill_viridis(discrete = TRUE,
                                                         name = "Race/Ethnicity")


ggplotly(p)
  
```


