---
title: "Geographical Distribution of Select Sexual Crimes"
author: "Amin Yakubu"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

Loading the required libraries

```{r}
library(tidyverse)
library(htmltools)
library(htmlwidgets)
library(leaflet)
library(leaflet.extras)
library(revgeo)

library(rgdal)
if (!require(geojsonio)) {
    install.packages("geojsonio")
    library(geojsonio)
}
library(sp)
library(maps)
library(ggmap)
library(maptools)
```

Reading in the datasets
```{r}
crime_df = readRDS(file = "./datasets/nyc_felony_crimes.rds")

sex_drug_weapons = crime_df %>% 
  filter(pd_cd %in% c(178, 694, 697, 176, 180, 153, 157, 177, 168, 159, 166, 164, 179, 155, 586, 696, # Sex related felony crimes
                      ## Drug related felony crimes
                      500, 501, 502, 503, 505, 507, 510, 512, 514, 515, 519, 520, 521, 523, 524, 529, 530, 531, 532, 568, 570,
                      ### Weapon related felony crimes
                      781, 792, 793, 796)) %>% 
  mutate(longitude = as.numeric(longitude),
         latitude = as.numeric(latitude)) %>% 
  select(boro_nm, cmplnt_fr_dt, cmplnt_fr_tm, latitude, longitude, ky_cd, ofns_desc, pd_cd, pd_desc, vic_race, vic_sex, year, prem_typ_desc) %>% 
  mutate(boro_nm = if_else(boro_nm == "staten island", "staten_island", boro_nm),
         crime_group = if_else(pd_cd %in% c(178, 694, 697, 176, 180, 153, 157, 177, 168, 159, 166, 164, 179, 155, 586, 696), "Sex-Related", 
                               if_else(pd_cd %in% c(500, 501, 502, 503, 505, 507, 510, 512, 514, 515, 519, 520, 521, 523, 524, 529, 530, 531, 532, 568, 570), "Drug-Related", 
                                       if_else(pd_cd %in% c(781, 792, 793, 796), "Weapon-Related", pd_cd))))
```


```{r}
sex_crimes_split = split(sex_crimes, sample(1:10, replace = F))

sex_crime_zip = sex_crimes %>% 
  mutate(zip = map2(.x = longitude, .y = latitude, ~ revgeo(longitude = .x , latitude= .y, output = "hash", item = "zip")))
```

Reverse geocoding to get the zip codes

```{r, eval = FALSE}
#### Sampling the just year 2017 and selecting all felony rape/attempted rape reports
zip_df = crime_df %>% filter(pd_cd %in% c(153, 157, 159, 155)) %>% filter(year == 2017) %>% 
  mutate(longitude = as.numeric(longitude),
         latitude = as.numeric(latitude))

### Sampling 500 because so as not to exceed the API query limit
zip_df_1 = zip_df %>% sample_n(500)

### Reverse geocoding each longitude and latitude
zip_names_1 = zip_df_1 %>% 
  mutate(zip = map2(.x = longitude, .y = latitude, ~ revgeo(longitude = .x , latitude= .y, output = "hash", item = "zip")))

### SAving the dataset so we don't call the API to everytime
saveRDS(zip_names_1, file = "datasets/nyc_rape_zip.rds")

### Using antijoin to find the other data set

zip_df_2 = anti_join(zip_df, zip_df_1, by = "cmplnt_num")

### Reverse geocoding to get their zip codes
zip_names_2 = zip_df_2 %>% 
  mutate(zip = map2(.x = longitude, .y = latitude, ~ revgeo(longitude = .x , latitude= .y, output = "hash", item = "zip")))

### SAving the dataset so we don't call the API to everytime
saveRDS(zip_names_2, file = "./datasets/nyc_rape_zip_2.rds")

```

```{r}
zip_df_1 = readRDS(file = "./datasets/nyc_rape_zip.rds")

zip_df_2 = readRDS(file = "./datasets/nyc_rape_zip_2.rds")

all_zip_df = bind_rows(zip_df_1, zip_df_2) 

all_zip_df = all_zip_df %>% mutate(zip = as.character(zip)) %>% 
  mutate(zip = str_replace(zip, "list\\(zip =", ""),
         zip = str_replace(zip, "\\)", ""),
         zipcode = gsub('"', '', zip),
         zipcode = str_replace(zipcode, ":[0-9][0-9][0-9][0-9][0-9]", ""),
         zipcode = str_replace(zipcode, "-[0-9][0-9][0-9][0-9]", ""),
         zipcode = as.numeric(zipcode),
         zipcode = as.factor(zipcode))

all_zip_df  %>%
  summarize_all(funs(sum(is.na(.))))

group_zip = all_zip_df %>% group_by(zipcode) %>% summarize(number = n())

map_url = "http://data.beta.nyc//dataset/3bf5fb73-edb5-4b05-bb29-7c95f4a727fc/resource/6df127b1-6d04-4bb7-b983-07402a2c3f90/download/f4129d9aa6dd4281bc98d0f701629b76nyczipcodetabulationareas.geojson"

download.file(map_url, "./datasets/nyc_zip_map.geojson")

```

```{r}
map_json <- geojson_read("./datasets/nyc_zip_map.geojson", what = "sp")
```

```{r}
map_json@data = 
  map_json@data %>% 
  left_join(group_zip, by = c("postalCode" = "zipcode")) %>% mutate(number = as.numeric(number)) %>% 
  mutate(number = if_else(is.na(number), 0, number))

```

Now let's plot our polygons

#### Distribution of reported rape and attempted rape in 2017 

```{r}

# create color palette with colorNumeric()
nyc_pal <- colorNumeric("Reds", domain = NULL)

map_json %>% 
  leaflet() %>% 
  #addTiles() %>% 
  #addProviderTiles("OpenStreetMap.BlackAndWhite")%>% 
  setView(lat = 40.7, lng = -74.0, zoom = 11) %>% 
  addPolygons(weight = 2, group = "zipcode",
              color = nyc_pal(map_json@data$number), 
              fillOpacity = 0.5, opacity = 5, 
              smoothFactor = 0.2, 
  # add labels that display mumber
              label = ~ paste(postalCode, borough, ':', number, sep = '\n'),
              # highlight polygons on hover
              highlight = highlightOptions(weight = 2, color = "black",
              bringToFront = TRUE)) %>% 
  addSearchFeatures(options = searchFeaturesOptions(zoom = 12), targetGroups = "zipcode") %>% 
   addLegend(pal = nyc_pal,
                   values = c(0:50),
                   opacity = 0.75,
                   title = "Number of reported rape",
                   position = "topleft") %>% addControl("Distrition of reported rape and attempted race cases by Zip codes", position = "topright")

```

#### Distribution of sexual related crimes in NYC

```{r}

sex_related = filter(sex_drug_weapons, crime_group == "Sex-Related") %>% 
  filter(!is.na(longitude) | !is.na(latitude))

drug_related = filter(sex_drug_weapons, crime_group == "Drug-Related") %>% 
  filter(!is.na(longitude) | !is.na(latitude))

weapon_related = filter(sex_drug_weapons, crime_group == "Weapon-Related") %>% 
  filter(!is.na(longitude) | !is.na(latitude))

pal <- 
   colorFactor(palette = c("blue", "red", "green"), 
               levels = c("Sex-Related", "Weapon-Related", "Drug-Related"))

m1 <- leaflet()  %>% 
  addTiles() %>% 
#Setting view on NYC. The values are the coordinates of NYC
    setView(lat = 40.7, lng = -74.0, zoom = 11) %>% 
  addCircleMarkers(data = sex_related,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "Sex-Related") %>% 
  addCircleMarkers(data = drug_related,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "Drug-Related") %>% 
  addCircleMarkers(data = weapon_related,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "Weapon-Related") 

```

Adding years 

```{r}
year_2014 = filter(sex_drug_weapons, year == 2014) %>% 
  filter(!is.na(longitude) | !is.na(latitude))

year_2015 = filter(sex_drug_weapons, year == 2015) %>% 
  filter(!is.na(longitude) | !is.na(latitude))

year_2016 = filter(sex_drug_weapons, year == 2016) %>% 
  filter(!is.na(longitude) | !is.na(latitude))

year_2017 =filter(sex_drug_weapons, year == 2017) %>% 
  filter(!is.na(longitude) | !is.na(latitude))

leaflet()  %>% 
  addTiles() %>% 
#Setting view on NYC. The values are the coordinates of NYC
    setView(lat = 40.7, lng = -74.0, zoom = 11) %>%
  addCircleMarkers(data = year_2014,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "2014") %>% 
  addCircleMarkers(data = year_2015,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "2015") %>% 
  addCircleMarkers(data = year_2016,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "2016") %>% 
  addCircleMarkers(data = year_2017,
                   lng = ~ longitude,
                   lat = ~ latitude, 
                   radius = 1,
                   color = ~pal(crime_group),
                   group = "2017") %>%
  addLayersControl(overlayGroups = c("2014", "2015", "2016", "2017")) %>% 
   addLegend(pal = pal, 
            values = c("Sex-Related", "Weapon-Related", "Drug-Related"),
            opacity = .5,
            title = "Crime Group",
            position = "topleft")
```











































