---
title: "Untitled"
author: "Amin Yakubu"
date: "11/18/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(maptools)
library(rgdal)
library(shapefiles)
library(ggmap)
library(knitr)
library(plotly)
library(p8105.datasets)
```

```{r}
crime_df = readRDS(file = "datasets/nyc_felony_misdemeanor.rds") 
```

```{r}
select_crimes = crime_df %>% filter(law_cat_cd == "felony") %>% 
  select(boro_nm, ky_cd, ofns_desc, longitude, latitude, x_coord_cd, y_coord_cd) %>% 
  filter(!is.na(ofns_desc)) %>% 
  mutate(ofns_desc = forcats::as_factor(ofns_desc)) %>% 
  mutate(longitude = as.numeric(longitude),
         latitude = as.numeric(latitude))

select_crimes %>% 
  group_by(boro_nm, x_coord_cd, y_coord_cd) %>% 
  summarize(n = n()) %>% View

```

```{r}

area <- rgdal::readOGR("/Users/amin/Desktop/NTA map/geo_export_992243af-bc24-493a-9edf-3828dab5d845.shp")

plot(area)

```

```{r}
x = crime_df %>% sample_n(5000) %>% 
  filter(ky_cd == 49 | ky_cd == 235 | ky_cd == 104 | ky_cd == 113) %>% 
  ggplot(aes(x = as.numeric(longitude), y = as.numeric(latitude), color = ky_cd)) +
  geom_point() +
  coord_cartesian() +
  theme_classic()

map <- select_crimes %>% sample_n(5000) %>% 
  ggplot(aes(x = longitude, y = latitude, color = ofns_desc)) +
  geom_polygon(data = area, aes(x = long, y = lat, group = group), colour = "black", fill = NA) +
  theme_void() + geom_point() + viridis::scale_color_viridis(discrete = TRUE) 
+  geom_text(data = cnames_nyc, aes(x = long, y = lat, label = id), size = 2)

ggplotly(map)
shp_nyc <- broom::tidy(area, region = "ntaname")

cnames_nyc <- aggregate(cbind(long, lat) ~ id, data=shp_nyc, FUN = mean)

```

```{r}
area_df = fortify(area)

map = ggplot() +
geom_path(data = area_df, 
          aes(x = long, y = lat, group = group),
          color = 'black', size = .2) + theme_void()

print(map)

map_projected <- map +
  coord_map()
  
print(map_projected)

ggplot(data = shp_nyc,
        mapping = aes(x = long, y = lat, group = id, fill = id)) +
  geom_polygon(data = area_df, color = "black", aes(x = long, y = lat, group = group)) + 
  coord_map(projection = "albers", lat0 = 39, lat1 = 45)
```


```{r}

```













