<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Statistical Analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="exploratory.html">Exploratory Analyses</a>
</li>
<li>
  <a href="flex_dashboard.html">Flex Dashboard</a>
</li>
<li>
  <a href="https://aminyakubu.shinyapps.io/NYC_crime_trend/">Shiny App</a>
</li>
<li>
  <a href="statistical_analysis.html">Statistical Analysis</a>
</li>
<li>
  <a href="acquiringdata.html">The Data</a>
</li>
<li>
  <a href="http://github.com/aminyakubu/nyc-crime/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Statistical Analysis</h1>

</div>


<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #337ab7;
}

.navbar-default .navbar-collapse, .navbar-default .navbar-form {
background-color: #337ab7;
}

.navbar-default {
background-color: #337ab7;
}

.navbar-default .navbar-nav>li>a {
color: white;
font-weight: bold;
}

.navbar-default .navbar-brand {
color: white;
font-weight: bold;
}

</style>
<div id="differences-in-length-of-crime" class="section level2">
<h2>Differences in Length of Crime</h2>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>In one of the exploratory analysis, we found that the average length of time of the reported crime (i.e., time between when it started and when it ended) differed for each felony type (sex-related, drug-related, and weapons-related). Results from that exploratory analysis is included below. We see that sex-related felonies last an average of 19.236 days, drug-related felonies last an average of 0.586 days, and weapons-related felonies last an average of 0.282 days.</p>
<table>
<thead>
<tr class="header">
<th align="left">Crime group</th>
<th align="right">Count</th>
<th align="right">Average time in days</th>
<th align="right">Standard deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drug-Related</td>
<td align="right">18293</td>
<td align="right">0.5862466</td>
<td align="right">12.315819</td>
</tr>
<tr class="even">
<td align="left">Sex-Related</td>
<td align="right">8646</td>
<td align="right">19.2362846</td>
<td align="right">83.297645</td>
</tr>
<tr class="odd">
<td align="left">Weapon-Related</td>
<td align="right">19753</td>
<td align="right">0.2820289</td>
<td align="right">9.101974</td>
</tr>
</tbody>
</table>
<p>We will assess whether this difference is statistically significant. Testing this difference can yield important insights regarding whether victims are disproportionately suffering the burden of certain crimes, in terms of absolute number of days. Finding a significant result may also suggest that certain felonies are more extensive and complicated, potentially more dangerous or violent, or may require more resources to deal with. Lastly, it may indicate that the victims are at a higher risk compared to those involved in other types of felonies.</p>
<p><br></p>
</div>
<div id="data-and-methods" class="section level3">
<h3>Data and Methods</h3>
<p>We first import the data below and clean up the data. We tidy the data so that Manhattan becomes the reference borough and drug-related felonies become the reference felony. Observations with missing information on when the crime started or when it ended were excluded.</p>
<p>Since we are testing the difference in means between three groups, we should be able to conduct an ANOVA test. To ensure that the assumptions of the ANOVA test are not violated, we test for homogeneity of variances. We used Levene’s test to test homogeneity of variances. We see from the results below that the p-value is less than 0.05. Therefore, the assumption of homogenous variances is not met.</p>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">df</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">group</td>
<td align="right">2</td>
<td align="right">903.7685</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">46689</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>We resort to using a non-parametric approach in detecting a difference of means between these three groups by utilizing the Kruskal-Wallis test. Using this test means that we do not make any underlying assumptions about the distribution of the three groups; since these groups potentially come from very different populations, a non-parametric approach seems best for this test.</p>
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="left">method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">6791.359</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="left">Kruskal-Wallis rank sum test</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>From the test above, it is evident that the p-value is less that 0.05. We conclude that at 5% level of significance, at least one of the average lengths of reported crimes (i.e., time between when the crime started and when it ended) is different among the three felony categories.</p>
<p>Since the Kruskal–Wallis test is significant, we now conduct a post-hoc analysis to determine which crime groups differ from each other level. We use the Dunn test for the post-hoc analysis.</p>
<pre><code>##                      Comparison           Z  P.unadj    P.adj
## 1    Drug-Related - Sex-Related -75.5637359 0.000000 0.000000
## 2 Drug-Related - Weapon-Related  -0.8243442 0.409744 0.409744
## 3  Sex-Related - Weapon-Related  75.8203110 0.000000 0.000000</code></pre>
<p><br></p>
</div>
<div id="results-and-discussion" class="section level3">
<h3>Results and Discussion</h3>
<p>The results show that there is a statistically significant difference between the average length of reported felonies for sex-related and drug-related felonies (p &lt; 0.005), as well as for sex-related and weapons-related felonies (p &lt;0.005). However, there isn’t a significant difference between drug-related and weapons-related felonies (p = 0.4097). All together, we have evidence suggesting that victims of sex-related felonies endure longer incidents, compared to victims of drug-related or weapons-related felonies.</p>
<p>The results of these tests suggest that victims of sex-related felonies endure significantly longer incidents compare to victims of drug-related or weapons-related felonies. This makes sense, considering that sex-related felonies include human trafficking, sexual abuse, and other cases in which the length of the crime is often dragged out compared to those within the other two felonies. Given this result, law enforcement, government, and public health officials should dedicate extra resources to prevent sex-related felonies and ensure that their agencies are adequately prepared and capable to resolve and manage sex-related felonies lasting longer periods of time.</p>
<p><br> <br></p>
</div>
<div id="association-between-borough-and-crime" class="section level3">
<h3>Association between borough and crime</h3>
<p>We examined the association between sex-related, drug-related, and weapons-related felonies and boroughs. We chose to look at this because the exploratory analyses suggested that the rates of these felonies differed, depending on the borough.</p>
<p><br></p>
<div id="model-statement-for-the-multinomial-logistic-regression-model" class="section level5">
<h5>Model Statement for the Multinomial Logistic Regression Model <br></h5>
<p><span class="math display">\[ln (\frac{P( crimegroup = drug-related)}{P(crime group = sex-related)}) = \beta_{10} + \beta_{11}(Bronx) + \beta_{12}(Brooklyn) + \beta_{13}(Queens) + \beta_{14}(Staten Island)\]</span> <br></p>
<p><span class="math display">\[ln(\frac{P(crimegroup = weapon-related)}{P(crime group = sex-related)}) = \beta_{20} + \beta_{21}(Bronx) + \beta_{22}(Brooklyn) + \beta_{23}(Queens) + \beta_{24}(Staten Island)\]</span></p>
<p>Drug-related group was chosen as reference group among the 3 types of felonies because it is the least serious of the 3 crime groups. For the boroughs, Manhattan was chosen as the reference group because it is widely thought to be the borough with least crime.</p>
<p><br></p>
</div>
<div id="cross-tabulation" class="section level4">
<h4>Cross tabulation</h4>
<p>We create a data table to organize the rates of drug-related, sex-related, and weapons-related felonies.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Drug-Related</th>
<th align="right">Sex-Related</th>
<th align="right">Weapon-Related</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>manhattan</td>
<td align="right">3566</td>
<td align="right">2084</td>
<td align="right">3550</td>
</tr>
<tr class="even">
<td>bronx</td>
<td align="right">6312</td>
<td align="right">1980</td>
<td align="right">4556</td>
</tr>
<tr class="odd">
<td>brooklyn</td>
<td align="right">5144</td>
<td align="right">2592</td>
<td align="right">7278</td>
</tr>
<tr class="even">
<td>queens</td>
<td align="right">2589</td>
<td align="right">1693</td>
<td align="right">3713</td>
</tr>
<tr class="odd">
<td>staten_island</td>
<td align="right">682</td>
<td align="right">297</td>
<td align="right">655</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th align="left">Crime group</th>
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard error</th>
<th align="right">statistic</th>
<th align="right">P value</th>
<th align="right">Odds ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Sex-Related</td>
<td align="left">Intercept</td>
<td align="right">0.5844049</td>
<td align="right">0.0275731</td>
<td align="right">-19.4813700</td>
<td align="right">0.0000000</td>
<td align="right">1.793923</td>
</tr>
<tr class="even">
<td align="left">Sex-Related</td>
<td align="left">Bronx</td>
<td align="right">0.5367635</td>
<td align="right">0.0377326</td>
<td align="right">-16.4896410</td>
<td align="right">0.0000000</td>
<td align="right">1.710462</td>
</tr>
<tr class="odd">
<td align="left">Sex-Related</td>
<td align="left">Brooklyn</td>
<td align="right">0.8622320</td>
<td align="right">0.0366125</td>
<td align="right">-4.0486419</td>
<td align="right">0.0000515</td>
<td align="right">2.368441</td>
</tr>
<tr class="even">
<td align="left">Sex-Related</td>
<td align="left">Queens</td>
<td align="right">1.1189544</td>
<td align="right">0.0416796</td>
<td align="right">2.6966344</td>
<td align="right">0.0070044</td>
<td align="right">3.061651</td>
</tr>
<tr class="odd">
<td align="left">Sex-Related</td>
<td align="left">Staten island</td>
<td align="right">0.7451797</td>
<td align="right">0.0747898</td>
<td align="right">-3.9327525</td>
<td align="right">0.0000840</td>
<td align="right">2.106820</td>
</tr>
<tr class="even">
<td align="left">Weapon-Related</td>
<td align="left">Intercept</td>
<td align="right">0.9955120</td>
<td align="right">0.0237090</td>
<td align="right">-0.1897204</td>
<td align="right">0.8495282</td>
<td align="right">2.706110</td>
</tr>
<tr class="odd">
<td align="left">Weapon-Related</td>
<td align="left">Bronx</td>
<td align="right">0.7250480</td>
<td align="right">0.0306600</td>
<td align="right">-10.4865465</td>
<td align="right">0.0000000</td>
<td align="right">2.064830</td>
</tr>
<tr class="even">
<td align="left">Weapon-Related</td>
<td align="left">Brooklyn</td>
<td align="right">1.4212297</td>
<td align="right">0.0298985</td>
<td align="right">11.7572104</td>
<td align="right">0.0000000</td>
<td align="right">4.142211</td>
</tr>
<tr class="odd">
<td align="left">Weapon-Related</td>
<td align="left">Queens</td>
<td align="right">1.4406084</td>
<td align="right">0.0348954</td>
<td align="right">10.4617057</td>
<td align="right">0.0000000</td>
<td align="right">4.223264</td>
</tr>
<tr class="even">
<td align="left">Weapon-Related</td>
<td align="left">Staten island</td>
<td align="right">0.9647314</td>
<td align="right">0.0596248</td>
<td align="right">-0.6021913</td>
<td align="right">0.5470468</td>
<td align="right">2.624083</td>
</tr>
</tbody>
</table>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
</div>
<div id="interpretation" class="section level3">
<h3>Interpretation</h3>
<p>The odds of sex-related crimes in manhattan is 1.79. The odds of sex related vs. drug-related crimes will increase by 1.71 if moving from Manhattan to Bronx. The odds of sex related vs. drug-related crimes will increase by 2.3684 if moving from Manhattan to Brooklyn. The odds of sex related vs. drug-related crimes will increase by 3.06 if moving from Manhattan to Queens. The odds of sex related vs. drug-related crimes will increase by 2.106 if moving from Manhattan to Staten Island.</p>
<p>The odds of weapon related crimes in manhattan is 2.7.</p>
<p>The odds of weapon related vs. drug related crimes will increase by 2.064 if moving from Manhattan to Bronx. The odds of weapon related vs drug related crimes will increase by 4.14 if moving from Manhattan to Brooklyn. The odds of weapon related vs drug related crimes will increase by 4.22 if moving from Manhattan to Queens. The odds of weapon related vs drug related crimes will increase by 2.62 if moving from Manhattan to Staten Island.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
